### ISSUE TITLE
Helm Chart - Add on Values option to add Grafana Init Image Repository

### ISSUE THREAD

**Issue by rodrigosandrin** [antrea-io/theia#889]
Good morning!

I would like to request if is possible to add some way to change the grafana init container repository.

I need to change all images to point to an internal repository we have this option in values.yaml:

``` 
image: 
    repository: "projects.registry.vmware.com/antrea/theia-grafana"
    pullPolicy: "IfNotPresent"
    tag: "9.1.6"
```
    
  However in build/charts/theia/templates/grafana/deployment.yaml the init container is hardcode.
  
  Also, maybe in this request we could add an option to change only the repository and keep the images in the other values, because to make this change we need to configure all images like this:
```  
clickhouse:
  image: 
    repository: "myinternalrepo.local/docker/antrea/theia-clickhouse-server"
  monitor:
    image:
      repository: "myinternalrepo.local/docker/antrea/theia-clickhouse-monitor"
  cluster:
    installZookeeper: 
      image:
        repository: "myinternalrepo.local/docker/antrea/theia-zookeeper"
grafana:
  image:
    repository: "myinternalrepo.local/docker/antrea/theia-grafana"
sparkOperator:
  enable: true
  image: 
    repository: "myinternalrepo.local/docker/antrea/theia-spark-operator"
theiaManager:
  image:
    repository: "myinternalrepo.local/docker/antrea/theia-manager"
```
    
I suggest to have something like "defaultRegistry".
   
Thanks!
